#Test

name: CI

#Controls
on:
#Triggers
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:
  
jobs:
   
 build:
   
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v2
    
    - name: Run a one-line script
      run: echo Hello, world!
      
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
   
# Installs Python 3.8
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'

# Installs Postgres, Meltano, and Meltano plugins
    - name: Install Meltano and project plugins
      run: |
        apt-get update && apt-get install libpq-dev
        pipx install meltano
        meltano install
    
